### ISSUE TITLE
mentors

### ISSUE THREAD

**Issue by mastervance16** [Gouripriya09/MasterVance#5]
change the whole page name and file name to **mentors**. Don't put mentor as name at any place. 

Redirect the **apply as mentor** button to this google form link : https://forms.gle/1Esq9Re3PxK6hPUR9

**Comment by Yogeshwar-CM** [comment]
Have added the form link but as of my knowledge , "Mentors" is the usage throughout the site, nowehere can i find Mentor.
Do let me know if im missing out anywhere

**Comment by Yogeshwar-CM** [comment]
I have checked again so closing this issue, Reopen if there is any
